require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrainCandiesController do

  # This should return the minimal set of attributes required to create a valid
  # BrainCandy. As you add validations to BrainCandy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrainCandiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all brain_candies as @brain_candies" do
      brain_candy = BrainCandy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brain_candies).should eq([brain_candy])
    end
  end

  describe "GET show" do
    it "assigns the requested brain_candy as @brain_candy" do
      brain_candy = BrainCandy.create! valid_attributes
      get :show, {:id => brain_candy.to_param}, valid_session
      assigns(:brain_candy).should eq(brain_candy)
    end
  end

  describe "GET new" do
    it "assigns a new brain_candy as @brain_candy" do
      get :new, {}, valid_session
      assigns(:brain_candy).should be_a_new(BrainCandy)
    end
  end

  describe "GET edit" do
    it "assigns the requested brain_candy as @brain_candy" do
      brain_candy = BrainCandy.create! valid_attributes
      get :edit, {:id => brain_candy.to_param}, valid_session
      assigns(:brain_candy).should eq(brain_candy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BrainCandy" do
        expect {
          post :create, {:brain_candy => valid_attributes}, valid_session
        }.to change(BrainCandy, :count).by(1)
      end

      it "assigns a newly created brain_candy as @brain_candy" do
        post :create, {:brain_candy => valid_attributes}, valid_session
        assigns(:brain_candy).should be_a(BrainCandy)
        assigns(:brain_candy).should be_persisted
      end

      it "redirects to the created brain_candy" do
        post :create, {:brain_candy => valid_attributes}, valid_session
        response.should redirect_to(BrainCandy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brain_candy as @brain_candy" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrainCandy.any_instance.stub(:save).and_return(false)
        post :create, {:brain_candy => { "name" => "invalid value" }}, valid_session
        assigns(:brain_candy).should be_a_new(BrainCandy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrainCandy.any_instance.stub(:save).and_return(false)
        post :create, {:brain_candy => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brain_candy" do
        brain_candy = BrainCandy.create! valid_attributes
        # Assuming there are no other brain_candies in the database, this
        # specifies that the BrainCandy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BrainCandy.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => brain_candy.to_param, :brain_candy => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested brain_candy as @brain_candy" do
        brain_candy = BrainCandy.create! valid_attributes
        put :update, {:id => brain_candy.to_param, :brain_candy => valid_attributes}, valid_session
        assigns(:brain_candy).should eq(brain_candy)
      end

      it "redirects to the brain_candy" do
        brain_candy = BrainCandy.create! valid_attributes
        put :update, {:id => brain_candy.to_param, :brain_candy => valid_attributes}, valid_session
        response.should redirect_to(brain_candy)
      end
    end

    describe "with invalid params" do
      it "assigns the brain_candy as @brain_candy" do
        brain_candy = BrainCandy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrainCandy.any_instance.stub(:save).and_return(false)
        put :update, {:id => brain_candy.to_param, :brain_candy => { "name" => "invalid value" }}, valid_session
        assigns(:brain_candy).should eq(brain_candy)
      end

      it "re-renders the 'edit' template" do
        brain_candy = BrainCandy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrainCandy.any_instance.stub(:save).and_return(false)
        put :update, {:id => brain_candy.to_param, :brain_candy => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brain_candy" do
      brain_candy = BrainCandy.create! valid_attributes
      expect {
        delete :destroy, {:id => brain_candy.to_param}, valid_session
      }.to change(BrainCandy, :count).by(-1)
    end

    it "redirects to the brain_candies list" do
      brain_candy = BrainCandy.create! valid_attributes
      delete :destroy, {:id => brain_candy.to_param}, valid_session
      response.should redirect_to(brain_candies_url)
    end
  end

end
